### ISSUE TITLE
[BUG] Spawner-Killer Module Blacklist Not Working

### ISSUE THREAD

**Issue by pelicano0** [Geik-xyz/Farmer-v6#78]
**Describe the bug**
In the Farmer-V6 plugin, the mob-blacklist section of the spawner-killer module is not working. Mobs that are blacklisted should not be killed when they spawn from a spawner, but they are still being killed.

**To Reproduce**
Activate the spawner-killer module in the Farmer-V6 plugin and add any creature to the blacklist. When you place the spawner for that creature, it will still be killed.

**Expected behavior**
The blacklist section in the Spawner-Killer module needs to be fixed. Entities that are added to the blacklist should not be killed.

**Screenshots**
No screenshot is needed.

**Logging**
There is no error message.

**Give me which version of Farmer do you use**
v6-b106

**Write your server version**
For example: PurpurMC 1.20.4

**Additional context**
There is no additional context.

**Comment by poyrazinan** [comment]
Please share your configuration settings of spawner-killer

**Comment by pelicano0** [comment]
```
# Spawner Killer Module
SpawnerKiller:
  # if you want to use spawner killer system
  # set feature to true.
  # and players with farmer.admin permission can give spawner killer.
  # you can disable buy feature and give farmer with command
  status: true
  # if you want to kill mobs without farmer set it false
  requireFarmer: false
  # cook foods on spawner drop
  cookFoods: false
  # remove mob can't see mob only spawn item.
  removeMob: true
  # default status for spawner killer when farmer place
  # if set true, farmer will be enable spawner killer by default
  # if set false, farmer will be disable spawner killer by default
  defaultStatus: true
  # custom perm for spawner killer status changer
  customPerm: farmer.spawnerkiller
  # set whitelist mobs for spawner killer
  # if you want to kill only whitelist mobs, set mode to whitelist
  # if you want to kill all mobs except blacklist mobs, set mode to blacklist
  mode: blacklist
  # You can add remove blacklist section
  # if you want to remove mobs from blacklist
  whitelist: []
  # You can add remove blacklist section
  # if you want to remove mobs from blacklist
  blacklist:
  - BLAZE``
```
